apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: restaurant-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: restaurant-auth:v2 # Ensure this image is built and available
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 50051
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: restaurant-config
                  key: NODE_ENV
            - name: DB_SYNCHRONIZE
              value: "true"
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: restaurant-config
                  key: POSTGRES_HOST
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: restaurant-config
                  key: POSTGRES_PORT
            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: restaurant-config
                  key: POSTGRES_DB
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: restaurant-secrets
                  key: POSTGRES_USER
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: restaurant-secrets
                  key: POSTGRES_PASSWORD
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: restaurant-config
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: restaurant-config
                  key: REDIS_PORT
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: restaurant-secrets
                  key: JWT_SECRET
            - name: ADMIN_REGISTRATION_KEY
              valueFrom:
                secretKeyRef:
                  name: restaurant-secrets
                  key: ADMIN_REGISTRATION_KEY
            - name: EMAIL_USER
              valueFrom:
                secretKeyRef:
                  name: restaurant-secrets
                  key: EMAIL_USER
            - name: EMAIL_PASS
              valueFrom:
                secretKeyRef:
                  name: restaurant-secrets
                  key: EMAIL_PASS
            - name: BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: restaurant-config
                  key: BASE_URL
            - name: CLIENT_URL
              valueFrom:
                configMapKeyRef:
                  name: restaurant-config
                  key: CLIENT_URL

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: restaurant-app
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
